### ISSUE TITLE
Running on Colab

### ISSUE THREAD

**Issue by bndxn** [jmather625/climatehack#2]
Hey there - thanks for making this repo public, I've been trying to run the code myself. Is it ok if I ask a potentially basic question about how it works please? @jmather625 

I've been trying to run train_unet.py on Colab as it needs so much RAM, but I'm getting an error at the end about the input dimensions: 

```
Could not gather input dimensions
[...]
RuntimeError: Given groups=24, expected weight to be at least 24 at dimension 0, but got weight of size [2, 1, 3, 1] instead
```

Is this an error that you encountered, and do you know if this is caused by the set up in some way? Thanks!

**Comment by bndxn** [comment]
The colab link is here https://colab.research.google.com/drive/1MEE4HfJ5PQP7P8sJh_O3P25qXosHabQ4?usp=sharing

**Comment by bndxn** [comment]
I resolved this, I realised it was because I'd changed the FORECAST variable to try to get it to run faster, which I think meant the outputs were the wrong size

**Comment by jmathur25** [comment]
Apologies for the late response. That does seem to be the issue. Glad it is fixed.
